package com.societycentral.dto.request;

import com.societycentral.model.TaskTargetType;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;

/**
 * Request DTO used when assigning a new task.
 *
 * BUSINESS RULES
 * --------------
 * • assignedBy is obtained from the authenticated user.
 * • issueDate is generated by the system.
 * • status is generated by the system.
 * • completionDate is generated when the task is completed.
 */
@Getter
@Setter
public class TaskRequestDTO {

    /**
     * Name/title of the task.
     */
    private String taskName;

    /**
     * Detailed description of the task.
     */
    private String taskDescription;

    /**
     * Date by which the task should be completed.
     */
    private LocalDate dueDate;

    /**
     * Determines whether the task is assigned to an
     * individual Executive or a society.
     */
    private TaskTargetType targetType;

    /**
     * Student number of the Executive receiving the task.
     *
     * Required only when targetType == INDIVIDUAL.
     */
    private String assignedTo;

    /**
     * Optional comments supplied by the assigner.
     */
    private String comment;


    /**
     * Society being assigned the task.
     * Required only when targetType == SOCIETY.
     */
    private String societyID;
}
