package com.societycentral.dto.response;

import com.societycentral.model.AttendingType;
import com.societycentral.model.Campus;
import com.societycentral.model.EventStatus;
import lombok.Builder;
import lombok.Data;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

/**
 * Response payload returned after an event has been successfully created
 * or retrieved.
 *
 * The DTO exposes event information required by the frontend without
 * returning the persistence entity directly.
 */
@Data
@Builder
public class EventResponseDTO {

    /**
     * Unique identifier generated by the backend for the event.
     */
    private String eventID;

    /**
     * Official name of the event.
     */
    private String eventName;

    /**
     * Date on which the event will take place.
     */
    private LocalDate eventDate;

    /**
     * Authoritative starting time of the event.
     */
    private LocalTime eventStartTime;

    /**
     * Authoritative ending time of the event.
     */
    private LocalTime eventEndTime;

    /**
     * Legacy starting-time field retained for existing consumers.
     *
     * @deprecated use {@link #eventStartTime}
     */
    @Deprecated
    private LocalTime eventTime;

    /**
     * Code of the authoritative venue record.
     */
    private String venueCode;

    /**
     * Venue name resolved from the database.
     */
    private String venueName;

    /**
     * Venue type resolved from the database.
     */
    private String venueType;

    /**
     * Maximum venue capacity resolved from the database.
     */
    private Integer venueCapacity;

    /**
     * Legacy venue-name field retained for existing consumers.
     *
     * @deprecated use {@link #venueName}
     */
    @Deprecated
    private String eventVenue;

    /**
     * NMU campus where the event will take place.
     */
    private Campus eventCampus;

    /**
     * Authoritative campus alias used by executive edit forms.
     *
     * <p>{@code eventCampus} remains available for existing consumers while
     * this field lets the edit UI reconstruct the selected venue without
     * inferring a differently named property.</p>
     */
    private Campus campus;

    /**
     * Detailed description of the event.
     */
    private String eventDescription;

    /**
     * Current version of the event advertisement.
     */
    private Integer advertisementVersion;

    /**
     * Current event workflow status.
     */
    private EventStatus eventStatus;

    /**
     * Date and time from which RSVPs may be submitted.
     */
    private LocalDateTime rsvpOpenDate;

    /**
     * Date and time after which RSVPs may no longer be submitted.
     */
    private LocalDateTime rsvpCloseDate;

    /**
     * Maximum number of attendees allowed.
     */
    private Integer eventLimit;

    /**
     * Defines who may attend the event.
     */
    private AttendingType attendingType;

    /**
     * Average rating assigned after the event has been completed.
     */
    private Double overallRating;

    /**
     * Legacy single-image URL retained for existing records.
     */
    @Deprecated
    private String imageUrl;

    /**
     * URL of the event poster image.
     */
    private String posterUrl;

    /**
     * URL of the event banner image.
     */
    private String bannerUrl;

    /**
     * Identifier of the society that created and primarily hosts the event.
     */
    private String primarySocietyID;

    /**
     * Name of the society that created and primarily hosts the event.
     */
    private String primarySocietyName;

    /**
     * Stable ownership alias used by the executive event-management screens.
     */
    private String societyID;

    /**
     * Stable society-name alias used by the executive event-management screens.
     */
    private String societyName;

    /**
     * Timestamp at which the event was first saved.
     */
    private LocalDateTime createdAt;

    /**
     * Timestamp of the latest edit or workflow transition.
     */
    private LocalDateTime updatedAt;

    /**
     * Most recent reviewer feedback for a rejected event, retained while the
     * executive revises the event.
     */
    private String rejectionReason;
}
