package com.societycentral.dto.response;

import com.societycentral.model.TaskStatus;
import com.societycentral.model.TaskTargetType;
import lombok.Builder;
import lombok.Getter;

import java.time.LocalDate;

/**
 * Response DTO returned after a task has been successfully
 * created or retrieved.
 *
 * BUSINESS RULES
 * --------------
 * • taskID is generated by the system.
 * • assignedBy is the authenticated Executive or SDO.
 * • issueDate is generated by the system.
 * • completionDate remains null until the task is completed.
 */
@Getter
@Builder
public class TaskResponseDTO {

    /**
     * Unique task identifier.
     */
    private String taskID;

    /**
     * Name/title of the task.
     */
    private String taskName;

    /**
     * Detailed description of the task.
     */
    private String taskDescription;

    /**
     * Date the task was issued.
     */
    private LocalDate issueDate;

    /**
     * Due date of the task.
     */
    private LocalDate dueDate;

    /**
     * Completion date.
     *
     * Will be null until the task is marked as complete.
     */
    private LocalDate completionDate;

    /**
     * Current task status.
     *
     * NOTE:
     * Within SocietyCentral, PENDING represents an active task
     * that has been assigned but not yet completed.
     */
    private TaskStatus status;

    /**
     * Email of the Executive or SDO who assigned the task.
     */
    private String assignedBy;

    /**
     * Assignment target type.
     */
    private TaskTargetType targetType;

    /**
     * Student number of the assigned Executive.
     */
    private String assignedTo;

    /**
     * Optional comments supplied by the assigner.
     */
    private String comment;
}
